#!/bin/bash

### BEGIN INIT INFO
# Provides:          UDP2RAW
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     
# Default-Stop:      0 1 6
# Short-Description: UDP2RAW-KCPTUN DAEMON for UBNT USG
# Description:       UDP2RAW-KCPTUN DAEMON for UBNT USG
### END INIT INFO

# Author: 

source /config/user-data/shadowsocks/scripts/file_list

DAEMON=$UDP2RAW
NAME=udp2rawd_kcptun
CONF=$MAIN_CONF
PID_DIR=/var/run
PID_FILE=$PID_DIR/$NAME.pid
RET_VAL=0
PID=0

if [ ! -x $DAEMON ]; then
  echo "The $DAEMON is not a executable file"
  exit 0
fi

if [ ! -f $CONF ]; then
    echo "$NAME configuration file $CONF not found"
    exit 1
fi

if [ ! -d $PID_DIR ]; then
    mkdir -p $PID_DIR
    if [ $? -ne 0 ]; then
        echo "Creating PID directory $PID_DIR failed"
        exit 1
    fi
fi

source $CONF

check_running() {
    if [ -r $PID_FILE ]; then
        read PID < $PID_FILE
        if [ -d "/proc/$PID" ]; then
            return 0
        else
            rm -f $PID_FILE
            return 1
        fi
    else
        return 2
    fi
}

do_status() {
    check_running
    case $? in
        0)
        echo "$NAME (pid $PID) is running..."
        ;;
        1|2)
        echo "$NAME is stopped"
        RET_VAL=1
        ;;
    esac
}

do_start() {
    if check_running; then
        echo "$NAME (pid $PID) is already running..."
        return 0
    fi
    $DAEMON -c -r$server:$udp2raw_kcptun_server_port -l0.0.0.0:`expr $local_port + 2` $udp2raw_param > /var/log/udp2rawd_kcptun.log 2>&1 &
    pgrep -n ${DAEMON##*/} > $PID_FILE

    if check_running; then
        echo "Starting $NAME success"
    else
        echo "Starting $NAME failed"
        RET_VAL=1
    fi
}

do_stop() {
    if check_running; then
        kill -9 $PID
        rm -f $PID_FILE
        echo "Stopping $NAME success"
    else
        echo "$NAME is stopped"
        RET_VAL=1
    fi
}

do_restart() {
    do_stop
    do_start
}

case "$1" in
    start|stop|restart|status)
    do_$1
    ;;
    *)
    echo "Usage: $0 { start | stop | restart | status }"
    RET_VAL=1
    ;;
esac

exit $RET_VAL
