#!/bin/bash

#File List
CHINADNS=/usr/bin/chinadns
CHINADNS_SRC=/config/user-data/shadowsocks/bin/chinadns

DNS2SOCKS=/usr/bin/dns2socks
DNS2SOCKS_SRC=/config/user-data/shadowsocks/bin/dns2socks

GFWLIST2DNSMASQ=/usr/bin/gfwlist2dnsmasq
GFWLIST2DNSMASQ_SRC=/config/user-data/shadowsocks/bin/gfwlist2dnsmasq

KCPTUN=/usr/bin/kcptun
KCPTUN_SRC=/config/user-data/shadowsocks/bin/kcptun

OBFS_LOCAL=/usr/bin/obfs-local
OBFS_LOCAL_SRC=/config/user-data/shadowsocks/bin/obfs-local

SS_LOCAL=/usr/bin/ss-local
SS_LOCAL_SRC=/config/user-data/shadowsocks/bin/ss-local

SS_REDIR=/usr/bin/ss-redir
SS_REDIR_SRC=/config/user-data/shadowsocks/bin/ss-redir

SS_TUNNEL=/usr/bin/ss-tunnel
SS_TUNNEL_SRC=/config/user-data/shadowsocks/bin/ss-tunnel

SSR_LOCAL=/usr/bin/ssr-local
SSR_LOCAL_SRC=/config/user-data/shadowsocks/bin/ssr-local

SSR_REDIR=/usr/bin/ssr-redir
SSR_REDIR_SRC=/config/user-data/shadowsocks/bin/ssr-redir

UDP2RAW=/usr/bin/udp2raw
UDP2RAW_SRC=/config/user-data/shadowsocks/bin/udp2raw

SS_WATCHDOG=/usr/bin/ss-watchdog
SS_WATCHDOG_SRC=/config/user-data/shadowsocks/bin/ss-watchdog

REFRESH_SS=/usr/bin/refresh-ss
REFRESH_SS_SRC=/config/user-data/shadowsocks/bin/refresh-ss

XT_SOCKET=/lib/modules/3.10.20-UBNT/kernel/net/netfilter/xt_socket.ko
XT_SOCKET_SRC=/config/user-data/shadowsocks/modules/xt_socket.ko

XT_TPROXY=/lib/modules/3.10.20-UBNT/kernel/net/netfilter/xt_TPROXY.ko
XT_TPROXY_SRC=/config/user-data/shadowsocks/modules/xt_TPROXY.ko

DNS2SOCKS_SERVICE=/etc/init.d/dns2socksd
DNS2SOCKS_SERVICE_SRC=/config/user-data/shadowsocks/services/dns2socksd

CHINADNS_SERVICE=/etc/init.d/chinadnsd
CHINADNS_SERVICE_SRC=/config/user-data/shadowsocks/services/chinadnsd

SS_LOCAL_SERVICE=/etc/init.d/ss-locald
SS_LOCAL_SERVICE_SRC=/config/user-data/shadowsocks/services/ss-locald

SS_REDIR_TCP_SERVICE=/etc/init.d/ss-redird_tcp
SS_REDIR_TCP_SERVICE_SRC=/config/user-data/shadowsocks/services/ss-redird_tcp

SS_REDIR_UDP_SERVICE=/etc/init.d/ss-redird_udp
SS_REDIR_UDP_SERVICE_SRC=/config/user-data/shadowsocks/services/ss-redird_udp

SSR_LOCAL_SERVICE=/etc/init.d/ssr-locald
SSR_LOCAL_SERVICE_SRC=/config/user-data/shadowsocks/services/ssr-locald

SSR_REDIR_TCP_SERVICE=/etc/init.d/ssr-redird_tcp
SSR_REDIR_TCP_SERVICE_SRC=/config/user-data/shadowsocks/services/ssr-redird_tcp

SSR_REDIR_UDP_SERVICE=/etc/init.d/ssr-redird_udp
SSR_REDIR_UDP_SERVICE_SRC=/config/user-data/shadowsocks/services/ssr-redird_udp

KCPTUN_SERVICE=/etc/init.d/kcptund
KCPTUN_SERVICE_SRC=/config/user-data/shadowsocks/services/kcptund

UDP2RAW_KCPTUN_SERVICE=/etc/init.d/udp2rawd_kcptun
UDP2RAW_KCPTUN_SERVICE_SRC=/config/user-data/shadowsocks/services/udp2rawd_kcptun

UDP2RAW_SS_SERVICE=/etc/init.d/udp2rawd_ss
UDP2RAW_SS_SERVICE_SRC=/config/user-data/shadowsocks/services/udp2rawd_ss

SS_WATCHDOG_SERVICE=/etc/init.d/ss-watchdogd
SS_WATCHDOG_SERVICE_SRC=/config/user-data/shadowsocks/services/ss-watchdogd

RULES_UPDATE=/etc/cron.weekly/rules_update
RULES_UPDATE_SRC=/config/user-data/shadowsocks/scripts/rules_update

SS_POSTCONFIG=/config/scripts/post-config.d/ss_postconfig
SS_POSTCONFIG_SRC=/config/user-data/shadowsocks/scripts/ss_postconfig

CHINA_LIST_RULES=/etc/dnsmasq.d/china_list.dnsmasq.conf
CHINA_LIST_RULES_SRC=/config/user-data/shadowsocks/rules/china_list.dnsmasq.conf

FOREIGN_LIST_RULES=/etc/dnsmasq.d/foreign_list.dnsmasq.conf
FOREIGN_LIST_RULES_SRC=/config/user-data/shadowsocks/rules/foreign_list.dnsmasq.conf

SS_RULES=/etc/dnsmasq.d/ss.dnsmasq.conf
SS_RULES_SRC=/config/user-data/shadowsocks/rules/ss.dnsmasq.conf

CHNROUTE_RULES=/config/user-data/shadowsocks/rules/chnroute.txt
CHNROUTE_RULES_CACHE=/config/user-data/shadowsocks/rules/chnroute.ipset
MAIN_CONF=/config/user-data/shadowsocks/config/main.conf
