#!/bin/bash

#Load File List
source /config/user-data/shadowsocks/scripts/file_list

cp -f $CHINADNS_SRC $CHINADNS
cp -f $DNS2SOCKS_SRC $DNS2SOCKS
cp -f $GFWLIST2DNSMASQ_SRC $GFWLIST2DNSMASQ
cp -f $KCPTUN_SRC $KCPTUN
cp -f $OBFS_LOCAL_SRC $OBFS_LOCAL
cp -f $SS_LOCAL_SRC $SS_LOCAL
cp -f $SS_REDIR_SRC $SS_REDIR
cp -f $SS_TUNNEL_SRC $SS_TUNNEL
cp -f $SSR_LOCAL_SRC $SSR_LOCAL
cp -f $SSR_REDIR_SRC $SSR_REDIR
cp -f $UDP2RAW_SRC $UDP2RAW
cp -f $REFRESH_SS_SRC $REFRESH_SS
cp -f $SS_WATCHDOG_SRC $SS_WATCHDOG
cp -f $DNS2SOCKS_SERVICE_SRC $DNS2SOCKS_SERVICE
cp -f $CHINADNS_SERVICE_SRC $CHINADNS_SERVICE
cp -f $SS_LOCAL_SERVICE_SRC $SS_LOCAL_SERVICE
cp -f $SS_REDIR_TCP_SERVICE_SRC $SS_REDIR_TCP_SERVICE
cp -f $SS_REDIR_UDP_SERVICE_SRC $SS_REDIR_UDP_SERVICE
cp -f $SSR_LOCAL_SERVICE_SRC $SSR_LOCAL_SERVICE
cp -f $SSR_REDIR_TCP_SERVICE_SRC $SSR_REDIR_TCP_SERVICE
cp -f $SSR_REDIR_UDP_SERVICE_SRC $SSR_REDIR_UDP_SERVICE
cp -f $KCPTUN_SERVICE_SRC $KCPTUN_SERVICE
cp -f $UDP2RAW_KCPTUN_SERVICE_SRC $UDP2RAW_KCPTUN_SERVICE
cp -f $UDP2RAW_SS_SERVICE_SRC $UDP2RAW_SS_SERVICE
cp -f $SS_WATCHDOG_SERVICE_SRC $SS_WATCHDOG_SERVICE
cp -f $RULES_UPDATE_SRC $RULES_UPDATE

kernel_verison=`uname -r`
if [ ! -e $XT_SOCKET -a "$kernel_verison" = "3.10.20-UBNT" ]; then
  cp $XT_SOCKET_SRC $XT_SOCKET
fi

if [ ! -e $XT_TPROXY -a "$kernel_verison" = "3.10.20-UBNT" ]; then
  cp $XT_TPROXY_SRC $XT_TPROXY
fi

update-rc.d ${CHINADNS_SERVICE##*/} stop 20 0 1 6 . > /dev/null 2>&1
update-rc.d ${DNS2SOCKS_SERVICE##*/} stop 21 0 1 6 . > /dev/null 2>&1
update-rc.d ${SSR_LOCAL_SERVICE##*/} stop 22 0 1 6 . > /dev/null 2>&1
update-rc.d ${SSR_REDIR_TCP_SERVICE##*/} stop 23 0 1 6 . > /dev/null 2>&1
update-rc.d ${SSR_REDIR_UDP_SERVICE##*/} stop 23 0 1 6 . > /dev/null 2>&1
update-rc.d ${SS_LOCAL_SERVICE##*/} stop 24 0 1 6 . > /dev/null 2>&1
update-rc.d ${SS_REDIR_TCP_SERVICE##*/} stop 25 0 1 6 . > /dev/null 2>&1
update-rc.d ${SS_REDIR_UDP_SERVICE##*/} stop 25 0 1 6 . > /dev/null 2>&1
update-rc.d ${KCPTUN_SERVICE##*/} stop 25 0 1 6 . > /dev/null 2>&1
update-rc.d ${UDP2RAW_KCPTUN_SERVICE##*/} stop 25 0 1 6 . > /dev/null 2>&1
update-rc.d ${UDP2RAW_SS_SERVICE##*/} stop 25 0 1 6 . > /dev/null 2>&1
update-rc.d ${SS_WATCHDOG_SERVICE##*/} stop 25 0 1 6 . > /dev/null 2>&1

depmod 
